package InterfaceOperationApp;
import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.Style;

/**
* InterfaceOperationApp/InterfaceOperatiosOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./InterfaceOperations.idl
* Friday, February 24, 2023 11:20:09 AM EST
*/
@WebService
@SOAPBinding(style=Style.RPC)
public interface InterfaceOperations 
{
  @WebMethod()
  String cancelMovieTickets (String customerID, String movieID, String movieName, int numberOfTickets);
  @WebMethod()
  String addMovieSlots (String movieId, String movieName, int bookingCapacity);
  @WebMethod()
  String removeMovieSlots (String movieId, String movieName);
  @WebMethod()
  String listMovieShowsAvailability (String movieName);
  @WebMethod()
  String getBookingSchedule (String customerID);
  @WebMethod()
  String bookMovieTickets (String customerID, String movieId, String movieName, int numberOfTickets);
  @WebMethod()
  String exchangeMovieTickets (String customerID, String movieId, String movieName, String new_movieId, String new_movieName, int numberOfTickets);
} // interface InterfaceOperatiosOperations
